### ISSUE TITLE
please add example of how to run program to README

### ISSUE THREAD

**Issue by ejessen** [olofk/ipyxact#1]
Hi,
I'm interested in parsing IP-XACT, and your tool looks great.
But could you post an example of how to run it?
I get errors when I do:
python gen_c_header.py generic_example.xml

It looks like that's how you want things done.

**Comment by olofk** [comment]
Hi. Thanks for reporting. I added some basic information and replaced the example XML file with a proper IP-Xact component. Please let me know if you find any more issues.

Cheers
