### ISSUE TITLE
Cannot obtain both attribute and value for a tag

### ISSUE THREAD

**Issue by solmartin** [olofk/ipyxact#20]
This is a completely arbitrary example, but take the following:

```
  <ipxact:tagOne>
    <ipxact:tagTwo name='a name'>0</ipxact:tagTwo>
  <ipxact:tagOne>
```

There's no way to get both the name attribute and the 0, as tags designated as CHILD or CHILDREN in the yaml override MEMBERS of the same name.

**Comment by solmartin** [comment]
@cdietschrun

**Comment by olofk** [comment]
The new API introduced in Ipyxact 0.3.0 should handle this.
