### ISSUE TITLE
Loading Xilinx File failes (root.tag == S+self._tag)

### ISSUE THREAD

**Issue by Botnic** [olofk/ipyxact#21]
Hello

I'm completely new to  this topic.
I would like to read and modify a Xilinx xci file.

>>> f1 = open('axis_switch_0.xci', 'r')
>>> from ipyxact.ipyxact import Component
>>> c1 = Component()
>>> c1.load(f1)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "ipyxact.py", line 106, in load
    raise Exception

What am I doing wrong?
The parsed file is attached.
[axis_switch_0.xci.zip](https://github.com/olofk/ipyxact/files/4994143/axis_switch_0.xci.zip)

Thank you for your help

**Comment by olofk** [comment]
The issue is that the xci file describes an IP-XACT *design* file, and not a *component*. The new API handles design files as well, but it is only available for IP-XACT 2014 and Vivado still only support IP-XACT 2009
