### ISSUE TITLE
[Q] Looking for a Tool - Register Read / Write UI based on IP-XACT

### ISSUE THREAD

**Issue by ameirson** [olofk/ipyxact#31]
Hi,

Looking for a tool that provides a UI based on an IP-XACT XML.

Of course such a tool would need read/write hooks for accessing the relevant target (or emulation) platform.

 

Thanks,

Alon

**Comment by bat52** [comment]
it is not UI, but has read/write hooks that can access real chips, and can parse IP-XACT format. 
Check it out here
https://github.com/bat52/cheap_pie

**Comment by ameirson** [comment]
Thanks !
Will look Into it.

**Comment by olofk** [comment]
For a GUI, you can look at [Kactus2](https://github.com/kactus2/kactus2dev)

**Comment by ameirson** [comment]
Thanks !
