### ISSUE TITLE
Required Python version

### ISSUE THREAD

**Issue by tudortimi** [olofk/ipyxact#4]
You should mention somewhere that the minimum required Python version is 2.7 (I guess). I tried running it with Python 2.6 (old Linux install) and I got a cryptic error message that made me scratch my head a bit.

**Comment by tudortimi** [comment]
Since some users might be running older Linux versions that ship with Python 2.6, it would be a good idea to use 'python2.7' in scripts instead of plain 'python'. This way you make it explicit that Python 2.7 is required and it's going to work when a user has two Python installations (2.6 from the OS and 2.7 installed in /usr/local/bin).

**Comment by olofk** [comment]
Hi,

You're right. I added a note that Python 2.7 is the lowest supported version. I don't want to explicitly write Python2.7 in the scripts however, as most users are probably already on python 3. This is still a bit of a mess in the python world

**Comment by tudortimi** [comment]
For my general knowledge: doesn't a Python 3 installation come with a bundled 2.7 interpreter?
